CREATE TABLE horoscope_readings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sign VARCHAR(20) UNIQUE NOT NULL,
  daily TEXT,
  weekly TEXT,
  monthly TEXT,
  is_updated BOOLEAN DEFAULT FALSE,
  is_read BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
